module.exports = {
  title: "PIEOS - Crypto-Backed Stablecoin PIE on EOS",
  keywords: [
    "PIEOS",
    "PIE",
    "EOS",
    "stablecoin",
    "DeFi",
    "privacy",
    "blockchain",
    "stake",
    "SCO",
  ],
  description: "PIEOS - crypto-backed stablecoin PIE providing optional privacy-protecting transaction features and interest-bearing savings accounts on EOSIO blockchain",
  url: "https://pieos.io",
  image: "/images/site_share_01.jpg",
  author: "PIEOS Builders",
  twitterUsername: "@PIEOS_io",
  trackingId: "UA-172440769-1",
  defaultLang: "en",
  langTextMap: {
    en: "English",
    ko: "한국어",
  },
};
